services: 
  nginx: 
    image: nginx:latest
    container_name: nginx
    ports: 
      - "80:80"
      - "443:443"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./nginx_data:/var/www/certbot
    network_mode: "host" 